sudo: required

services:
    - docker

before_install:
    - docker build -t omaroid/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true omaroid/react-test npm test 

after_success:
    - docker build -t omaroid/multi-client ./client
    - docker build -t omaroid/multi-nginx ./nginx
    - docker build -t omaroid/multi-server ./server
    - docker build -t omaroid/multi-worker ./worker
    # Login to Docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push omaroid/multi-client
    - docker push omaroid/multi-nginx
    - docker push omaroid/multi-server
    - docker push omaroid/multi-worker